apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - image: horllymobile/reverseproxy:v1
          name: reverseproxy
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "env"]
          env:
            - name: "AWS_PROFILE"
              valueFrom:
                configMapKeyRef:
                  name: "env-configmap"
                  key: AWS_PROFILE
            - name: "AWS_REGION"
              valueFrom:
                configMapKeyRef:
                  name: "env-configmap"
                  key: "AWS_REGION"
            - name: "URL"
              valueFrom:
                configMapKeyRef:
                  name: "env-configmap"
                  key: "URL"
            - name: "AWS_BUCKET"
              valueFrom:
                configMapKeyRef:
                  name: "env-configmap"
                  key: "AWS_BUCKET"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"       
          ports:
          - containerPort: 8080
      restartPolicy: Always